### ISSUE TITLE
Can't build on macOS 11.5.2 - 'malloc.h' file not found

### ISSUE THREAD

**Issue by ds8k** [libretro/mupen64plus-libretro-nx#386]
Running `make` in the root directory fails with this error:

```
./GLideN64/src/PaletteTexture.h:7:10: fatal error: 'malloc.h' file not found
#include <malloc.h>
```
